export const CREATE_ITEM = "CREATE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const CHANGE_CHECKBOX_STATUS = "CHANGE_CHECKBOX_STATUS";

export const CREATE_CHECK_CARD = "CREATE_CHECK_CARD";
export const CREATE_TEXT_CARD = "CREATE_TEXT_CARD";

export const CREATE_LABEL = "CREATE_LABEL";
export const UPDATE_LABEL = "UPDATE_LABEL";
export const DELETE_LABEL = " DELETE_LABEL";

export const CREATE_LABEL_IN_CARD = "CREATE_LABEL_IN_CARD";
export const UPDATE_LABEL_IN_CARD = "UPDATE_LABEL_IN_CARD";
export const DELETE_LABEL_IN_CARD = "DELETE_LABEL_IN_CARD";

export const DELETE_LABEL_IN_ALL_CARD = "DELETE_LABEL_IN_ALL_CARD";
